/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "agent_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace uber { namespace jaeger { namespace agent { namespace thrift {

}}}} // namespace
