// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "BaggageRestrictionManager.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::jaegertracing::thrift;

class BaggageRestrictionManagerHandler : virtual public BaggageRestrictionManagerIf {
 public:
  BaggageRestrictionManagerHandler() {
    // Your initialization goes here
  }

  /**
   * getBaggageRestrictions retrieves the baggage restrictions for a specific service.
   * Usually, baggageRestrictions apply to all services however there may be situations
   * where a baggageKey might only be allowed to be set by a specific service.
   * 
   * @param serviceName
   */
  void getBaggageRestrictions(std::vector<BaggageRestriction> & _return, const std::string& serviceName) {
    // Your implementation goes here
    printf("getBaggageRestrictions\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<BaggageRestrictionManagerHandler> handler(new BaggageRestrictionManagerHandler());
  shared_ptr<TProcessor> processor(new BaggageRestrictionManagerProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

