/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "baggage_constants.h"

namespace uber { namespace jaeger { namespace thrift {

const baggageConstants g_baggage_constants;

baggageConstants::baggageConstants() {
}

}}} // namespace

