/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef sampling_CONSTANTS_H
#define sampling_CONSTANTS_H

#include "sampling_types.h"

namespace uber { namespace jaeger { namespace thrift { namespace sampling_manager {

class samplingConstants {
 public:
  samplingConstants();

};

extern const samplingConstants g_sampling_constants;

}}}} // namespace

#endif
