/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "agent_constants.h"

namespace uber { namespace jaeger { namespace agent { namespace thrift {

const agentConstants g_agent_constants;

agentConstants::agentConstants() {
}

}}}} // namespace

