/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "jaeger_constants.h"

namespace uber { namespace jaeger { namespace thrift {

const jaegerConstants g_jaeger_constants;

jaegerConstants::jaegerConstants() {
}

}}} // namespace

